package dev.integratepbr.model.discovery;

import com.google.gson.*;
import com.mojang.blaze3d.platform.NativeImage;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.*;
import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.regex.Pattern;

/** Current recipe only; no source.run, transforms, GPU access or load-time claim. */
public final class AtlasSourceAttribution {
    static final String BLOCKS="minecraft:textures/atlas/blocks.png",DEFINITION="minecraft:atlases/blocks.json";
    interface Open {InputStream get() throws Exception;}
    record File(String provider,Open open,String metadataState){}
    interface Access {List<File> stack(String id)throws Exception;File effective(String id)throws Exception;Map<String,File> list(String prefix)throws Exception;}
    interface Pixels {int width();int height();boolean rgba();int abgr(int x,int y)throws Exception;}
    interface Sampler {boolean identity(String atlas,String sprite,Object token)throws Exception;Boolean metadataEmpty(Object token)throws Exception;Pixels pixels(Object token)throws Exception;}
    public record Captured(byte[] bytes,Map<String,byte[]> assets){public Captured{bytes=bytes.clone();Map<String,byte[]> copy=new TreeMap<>();assets.forEach((k,v)->copy.put(k,v.clone()));assets=Collections.unmodifiableMap(copy);}@Override public byte[] bytes(){return bytes.clone();}@Override public Map<String,byte[]> assets(){Map<String,byte[]> c=new TreeMap<>();assets.forEach((k,v)->c.put(k,v.clone()));return c;}}
    static boolean excluded(String provider){return ResourceSnapshot.GENERATED_PACK.equals(provider);}
    static JsonObject obj(){return new JsonObject();}
    static void nil(JsonObject o,String k){o.add(k,JsonNull.INSTANCE);}
    static String string(JsonElement e){if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isString())throw new IllegalArgumentException("string required");String v=e.getAsString();if(!RuntimeModelObservation.unicode(v)||v.getBytes(StandardCharsets.UTF_8).length>512)throw new IllegalArgumentException("string bound");return v;}
    static String id(JsonElement e){String value=string(e);if(!value.contains(":"))value="minecraft:"+value;if(!RuntimeModelObservation.resourceId(value))throw new IllegalArgumentException("unsafe ID");return value;}
    static String png(String resource){String[] p=resource.split(":",2);return p[0]+":textures/"+p[1]+".png";}
    static void shape(JsonObject o,Set<String> required,Set<String> optional){if(!o.keySet().containsAll(required))throw new IllegalArgumentException("missing fields");Set<String> allowed=new HashSet<>(required);allowed.addAll(optional);if(!allowed.containsAll(o.keySet()))throw new IllegalArgumentException("unknown fields");}
    static String path(JsonElement e,boolean trailing){String v=string(e);String test=trailing&&v.endsWith("/")?v.substring(0,v.length()-1):v;if(!test.isEmpty()&&(test.startsWith("/")||test.contains(":")||test.contains("\\")||Arrays.stream(test.split("/",-1)).anyMatch(p->p.isEmpty()||p.equals(".")||p.equals(".."))))throw new IllegalArgumentException("unsafe prefix");return v;}
    static String operation(JsonObject source){return id(source.get("type")).replace("minecraft:","");}
    static void declaration(JsonObject s){String type=operation(s);switch(type){case "single"->{shape(s,Set.of("type","resource"),Set.of("sprite"));id(s.get("resource"));if(s.has("sprite"))id(s.get("sprite"));}case "directory"->{shape(s,Set.of("type","source","prefix"),Set.of());path(s.get("source"),true);path(s.get("prefix"),true);}case "filter"->{shape(s,Set.of("type","pattern"),Set.of());JsonObject p=s.getAsJsonObject("pattern");shape(p,Set.of(),Set.of("namespace","path"));for(String k:p.keySet()){String regex=string(p.get(k));if(regex.getBytes(StandardCharsets.UTF_8).length>256)throw new IllegalArgumentException("regex bound");Pattern.compile(regex);}}case "unstitch"->{shape(s,Set.of("type","resource","regions"),Set.of("divisor_x","divisor_y"));id(s.get("resource"));for(String k:List.of("divisor_x","divisor_y"))if(s.has(k))number(s.get(k));JsonArray regions=s.getAsJsonArray("regions");if(regions.isEmpty()||regions.size()>2048)throw new IllegalArgumentException("regions bound");for(JsonElement e:regions){JsonObject r=e.getAsJsonObject();shape(r,Set.of("sprite","x","y","width","height"),Set.of());id(r.get("sprite"));for(String k:List.of("x","y","width","height"))number(r.get(k));}}case "paletted_permutations"->{shape(s,Set.of("type","textures","palette_key","permutations"),Set.of());id(s.get("palette_key"));JsonArray textures=s.getAsJsonArray("textures");if(textures.size()>2048)throw new IllegalArgumentException("texture bound");for(JsonElement e:textures)id(e);JsonObject permutations=s.getAsJsonObject("permutations");if(permutations.size()>2048)throw new IllegalArgumentException("permutation bound");for(var e:permutations.entrySet()){String key=string(new JsonPrimitive(e.getKey()));id(e.getValue());if(!key.matches("[a-z0-9_./-]*"))throw new IllegalArgumentException("unsafe suffix");}}default->{/* Unknown type conservatively poisons atlas, never run it. */}}}
    static JsonElement json(com.google.gson.stream.JsonReader reader,int depth,int[] nodes)throws IOException{if(depth>32||++nodes[0]>200000)throw new IOException("JSON structure budget");return switch(reader.peek()){case BEGIN_OBJECT->{JsonObject o=obj();reader.beginObject();while(reader.hasNext()){String key=reader.nextName();if(++nodes[0]>200000||depth+1>32)throw new IOException("JSON structure budget");if(o.has(key)||!RuntimeModelObservation.unicode(key))throw new IOException("duplicate/unsafe key");o.add(key,json(reader,depth+1,nodes));}reader.endObject();yield o;}case BEGIN_ARRAY->{JsonArray a=new JsonArray();reader.beginArray();while(reader.hasNext())a.add(json(reader,depth+1,nodes));reader.endArray();yield a;}case STRING->{String v=reader.nextString();if(!RuntimeModelObservation.unicode(v))throw new IOException("unsafe scalar");yield new JsonPrimitive(v);}case NUMBER->{String v=reader.nextString();double n=Double.parseDouble(v);if(!Double.isFinite(n))throw new IOException("nonfinite scalar");yield new JsonPrimitive(new java.math.BigDecimal(v));}case BOOLEAN->new JsonPrimitive(reader.nextBoolean());case NULL->{reader.nextNull();yield JsonNull.INSTANCE;}default->throw new IOException("invalid JSON token");};}
    static JsonObject definitionJson(byte[] bytes)throws Exception {String text=StandardCharsets.UTF_8.newDecoder().onMalformedInput(java.nio.charset.CodingErrorAction.REPORT).onUnmappableCharacter(java.nio.charset.CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString();try(var reader=new com.google.gson.stream.JsonReader(new StringReader(text))){reader.setLenient(false);JsonElement value=json(reader,0,new int[1]);if(reader.peek()!=com.google.gson.stream.JsonToken.END_DOCUMENT)throw new IOException("trailing JSON");return value.getAsJsonObject();}}
    static double number(JsonElement e){if(e==null||!e.isJsonPrimitive()||!e.getAsJsonPrimitive().isNumber()||!Double.isFinite(e.getAsDouble()))throw new IllegalArgumentException("finite numeric required");return e.getAsDouble();}
    static String pixelDigest(Pixels pixels)throws Exception {MessageDigest digest=MessageDigest.getInstance("SHA-256");digest.update("IPBR_RGBA8_V1\0".getBytes(StandardCharsets.US_ASCII));digest.update(ByteBuffer.allocate(8).putInt(pixels.width()).putInt(pixels.height()).array());for(int y=0;y<pixels.height();y++)for(int x=0;x<pixels.width();x++){int n=pixels.abgr(x,y);digest.update(new byte[]{(byte)n,(byte)(n>>>8),(byte)(n>>>16),(byte)(n>>>24)});}return HexFormat.of().formatHex(digest.digest());}
    static final class Limits {int layers=64,fileDefinition=262144,filePng=4194304,definitionTotal=4194304,evidenceTotal=33554432,resources=1024,calls=8192,sources=2048,listEach=4096,listTotal=8192,expanded=8192,traceEach=1024,traceTotal=16384,pixels=4194304,nodes=200000,depth=32;}
    static boolean structure(JsonElement value,int depthLimit,int nodeLimit){record Node(JsonElement e,int depth){}ArrayDeque<Node> stack=new ArrayDeque<>();stack.add(new Node(value,0));int count=0;while(!stack.isEmpty()){var n=stack.removeLast();if(++count>nodeLimit||n.depth()>depthLimit)return false;var e=n.e();if(e==null||e.isJsonNull())continue;if(e.isJsonObject()){if(e.getAsJsonObject().size()*2L+count+stack.size()>nodeLimit)return false;for(var p:e.getAsJsonObject().entrySet()){stack.add(new Node(new JsonPrimitive(p.getKey()),n.depth()+1));stack.add(new Node(p.getValue(),n.depth()+1));}}else if(e.isJsonArray()){if(e.getAsJsonArray().size()+count+stack.size()>nodeLimit)return false;for(var child:e.getAsJsonArray())stack.add(new Node(child,n.depth()+1));}else if(e.isJsonPrimitive()){var p=e.getAsJsonPrimitive();if(p.isString()&&!RuntimeModelObservation.unicode(p.getAsString())||p.isNumber()&&!Double.isFinite(p.getAsDouble()))return false;}}return true;}
    static File resourceFile(Resource r){return new File(r.sourcePackId(),r::open,"unknown");}
    static final class Evaluation {
        final Access access;final Sampler sampler;final RuntimeModelObservation.Bundle bundle;final JsonObject runtime,root=obj();final JsonArray resources=new JsonArray(),atlases=new JsonArray(),mappings=new JsonArray(),omissions=new JsonArray();final Map<String,byte[]> assets=new TreeMap<>();final Map<String,Integer> captured=new HashMap<>();final Limits limits;final Map<String,File> effectiveCache=new HashMap<>();final Map<String,List<File>> stackCache=new HashMap<>();final Map<String,Map<String,File>> listCache=new HashMap<>();final IdentityHashMap<File,Map<String,byte[]>> readCache=new IdentityHashMap<>();final IdentityHashMap<File,Map<String,Integer>> resourceCache=new IdentityHashMap<>();int calls,sources,listing,traceCount,expanded;long definitionBytes,evidenceBytes,samplePixels;boolean incomplete;
        Evaluation(RuntimeModelObservation.Bundle bundle,Access access,Sampler sampler){this(bundle,access,sampler,new Limits());}
        Evaluation(RuntimeModelObservation.Bundle bundle,Access access,Sampler sampler,Limits limits){this.limits=limits;this.bundle=bundle;this.access=access;this.sampler=sampler;runtime=JsonParser.parseString(new String(bundle.bytes(),StandardCharsets.UTF_8)).getAsJsonObject();root.addProperty("schema_version",1);root.addProperty("adapter","blocks_current_recipe_v2");root.add("origin",runtime.get("origin"));root.add("selected_owner",runtime.get("selected_owner").deepCopy());root.addProperty("runtime_sha256",ResourceSnapshot.digest(bundle.bytes()));for(String k:List.of("load_time_provenance_verified","rendered_frame_verified","eligible_for_generation"))root.addProperty(k,false);root.addProperty("pixel_digest_convention","ipbr_rgba8_dimensions_v1");root.add("atlases",atlases);root.add("resources",resources);root.add("mappings",mappings);root.add("omissions",omissions);}
        void reason(String code){incomplete=true;if(omissions.size()<256){JsonObject o=obj();o.addProperty("code",code);o.addProperty("detail","bounded current recipe capture incomplete");omissions.add(o);}}
        void call(){if(calls>=limits.calls)throw new IllegalArgumentException("lookup_open_budget");calls++;if(calls>limits.calls)throw new IllegalArgumentException("lookup_open_budget");}
        File effective(String id)throws Exception{if(effectiveCache.containsKey(id))return effectiveCache.get(id);call();File result=access.effective(id);effectiveCache.put(id,result);return result;}
        List<File> stack(String id)throws Exception{if(stackCache.containsKey(id))return stackCache.get(id);call();List<File> result=access.stack(id);if(result==null||result.size()>limits.layers)throw new IllegalArgumentException("definition_layers");result=List.copyOf(result);stackCache.put(id,result);return result;}
        Map<String,File> listing(String prefix)throws Exception{if(listCache.containsKey(prefix))return listCache.get(prefix);if(listing>=limits.listTotal)throw new IllegalArgumentException("listing_budget");call();Map<String,File> result=access.list(prefix);if(result==null||result.size()>limits.listEach||listing+result.size()>limits.listTotal)throw new IllegalArgumentException("listing_budget");listing+=result.size();result=Map.copyOf(result);listCache.put(prefix,result);return result;}
        int resource(String role,String id,File f,Integer layer)throws Exception {
            if(f==null)throw new IllegalArgumentException("missing resource");String cacheKey=role+"|"+id;if(layer==null&&resourceCache.containsKey(f)&&resourceCache.get(f).containsKey(cacheKey))return resourceCache.get(f).get(cacheKey);
            if(resources.size()>=limits.resources)throw new IllegalArgumentException("resource_budget");String provider=string(new JsonPrimitive(f.provider()));if(provider.isEmpty())throw new IllegalArgumentException("provider empty");boolean excludedBytes=excluded(provider)&&!role.equals("definition");byte[] bytes=null;String hash=null,path=null;
            if(!excludedBytes){Map<String,byte[]> cached=readCache.get(f);bytes=cached==null?null:cached.get(cacheKey);if(bytes==null){long remaining=limits.evidenceTotal-evidenceBytes;if(role.equals("definition"))remaining=Math.min(remaining,limits.definitionTotal-definitionBytes);int cap=(int)Math.min(role.equals("png")?limits.filePng:limits.fileDefinition,remaining);if(cap<=0)throw new IllegalArgumentException("aggregate_read_budget");call();try(InputStream in=f.open().get()){bytes=in.readNBytes(cap+1);}if(bytes.length>cap)throw new IllegalArgumentException("file_budget");readCache.computeIfAbsent(f,k->new HashMap<>()).put(cacheKey,bytes.clone());}
                hash=ResourceSnapshot.digest(bytes);if(role.equals("definition")){if(definitionBytes+bytes.length>limits.definitionTotal||evidenceBytes+bytes.length>limits.evidenceTotal)throw new IllegalArgumentException("definition_budget");definitionBytes+=bytes.length;path="evidence/atlas/definitions/"+layer+"-"+hash+".json";}else path="evidence/atlas/"+role+"/"+ResourceSnapshot.digest((role+"\0"+id+"\0"+provider+"\0"+hash).getBytes(StandardCharsets.UTF_8))+(role.equals("png")?".png":".mcmeta");String key=role+"|"+id+"|"+provider+"|"+hash;if(layer==null&&captured.containsKey(key)){int existing=captured.get(key);resourceCache.computeIfAbsent(f,k->new HashMap<>()).put(cacheKey,existing);return existing;}if(evidenceBytes+bytes.length>limits.evidenceTotal)throw new IllegalArgumentException("evidence_budget");evidenceBytes+=bytes.length;assets.put(path,bytes.clone());if(layer==null)captured.put(key,resources.size());}
            JsonObject r=obj();int index=resources.size();r.addProperty("asset_id",index);r.addProperty("role",role);r.addProperty("resource_id",id);r.addProperty("source_pack_id",provider);RuntimeModelObservation.nullable(r,"layer",layer);RuntimeModelObservation.nullable(r,"source_path",path);RuntimeModelObservation.nullable(r,"sha256",hash);RuntimeModelObservation.nullable(r,"byte_count",bytes==null?null:bytes.length);r.addProperty("generated_excluded",excluded(provider));r.addProperty("metadata_state",role.equals("png")?f.metadataState():"not_applicable");resources.add(r);if(layer==null)resourceCache.computeIfAbsent(f,k->new HashMap<>()).put(cacheKey,index);return index;
        }
        JsonObject mapping(JsonObject sprite){JsonObject m=obj();for(String k:List.of("sprite_handle","sprite_id","atlas_id"))m.add(k,sprite.get(k));for(String k:List.of("actual_candidate","external_source_candidate","winning_definition","winning_source_index"))nil(m,k);m.addProperty("recipe_state","absent");m.add("trace",new JsonArray());m.add("reason_codes",new JsonArray());JsonObject sample=obj();for(String k:List.of("identity_before","identity_after","width","height","metadata_empty","pixel_sha256"))nil(sample,k);sample.add("reason_codes",new JsonArray());m.add("sample",sample);m.addProperty("status","missing_source");return m;}
        void trace(JsonObject m,int definition,int index,String operation,String effect){JsonArray t=m.getAsJsonArray("trace");if(t.size()>=limits.traceEach||++traceCount>limits.traceTotal)throw new IllegalArgumentException("trace_budget");JsonObject e=obj();e.addProperty("definition_asset_id",definition);e.addProperty("source_index",index);e.addProperty("operation",operation);e.addProperty("effect",effect);t.add(e);}
        void add(JsonObject m,String file,File winner,int definition,int index,String operation,boolean transformed)throws Exception{if(winner==null){trace(m,definition,index,operation,"missing");return;}trace(m,definition,index,operation,transformed?"transformed":m.get("recipe_state").getAsString().equals("absent")?"add":"replace");m.addProperty("winning_definition",definition);m.addProperty("winning_source_index",index);m.addProperty("recipe_state",transformed?"transformed":"direct");nil(m,"actual_candidate");nil(m,"external_source_candidate");if(transformed){m.addProperty("status","transformed_source_unsupported");return;}int actual=resource("png",file,winner,null);m.addProperty("actual_candidate",actual);boolean excludedRecipe=resources.get(definition).getAsJsonObject().get("generated_excluded").getAsBoolean();m.addProperty("status",excluded(winner.provider())||excludedRecipe?"generated_source_excluded":"candidate");for(File lower:stack(file)){if(!excluded(lower.provider()))m.addProperty("external_source_candidate",resource("png",file,lower,null));}
            File metadata=effective(file+".mcmeta");if(metadata!=null){resource("metadata",file+".mcmeta",metadata,null);if(m.get("status").getAsString().equals("candidate"))m.addProperty("status","unsupported_static_metadata");}if(!Set.of("empty","unknown").contains(winner.metadataState())&&m.get("status").getAsString().equals("candidate"))m.addProperty("status","unsupported_static_metadata");}
        void replay(JsonArray layers,JsonObject atlas)throws Exception{
            for(JsonElement layer:layers){JsonObject l=layer.getAsJsonObject();int def=l.get("asset_id").getAsInt();String definitionPath=resources.get(def).getAsJsonObject().get("source_path").getAsString();JsonObject document=definitionJson(assets.get(definitionPath));if(!structure(document,limits.depth,limits.nodes))throw new IllegalArgumentException("unsafe_definition");shape(document,Set.of("sources"),Set.of());JsonArray declarations=document.getAsJsonArray("sources");if(declarations==null||sources+declarations.size()>limits.sources)throw new IllegalArgumentException("source_budget");sources+=declarations.size();for(JsonElement e:declarations){JsonObject source=e.getAsJsonObject();declaration(source);String op=operation(source);long count=op.equals("unstitch")?source.getAsJsonArray("regions").size():op.equals("paletted_permutations")?(long)source.getAsJsonArray("textures").size()*source.getAsJsonObject("permutations").size():0;if(count+expanded>limits.expanded)throw new IllegalArgumentException("transform_expansion_budget");expanded+=(int)count;}
                for(int index=0;index<declarations.size();index++){JsonObject s=declarations.get(index).getAsJsonObject();String op=operation(s);if(!Set.of("single","directory","filter","unstitch","paletted_permutations").contains(op)){reason("custom_source_unsupported");for(JsonElement e:mappings)if(e.getAsJsonObject().get("atlas_id").getAsString().equals(BLOCKS))trace(e.getAsJsonObject(),def,index,"unknown","unknown");continue;}
                    Map<String,File> directory=null;if(op.equals("directory")){String prefix="textures/"+path(s.get("source"),true);directory=listing(prefix);}
                    for(JsonElement e:mappings){JsonObject m=e.getAsJsonObject();if(!m.get("atlas_id").getAsString().equals(BLOCKS))continue;String sprite=m.get("sprite_id").getAsString();
                        switch(op){case "single"->{String resource=id(s.get("resource")),target=s.has("sprite")?id(s.get("sprite")):resource;if(target.equals(sprite))add(m,png(resource),effective(png(resource)),def,index,op,false);}case "directory"->{String source="textures/"+path(s.get("source"),true),prefix=path(s.get("prefix"),true);for(var entry:new TreeMap<>(directory).entrySet()){String f=id(new JsonPrimitive(entry.getKey()));String[] parts=f.split(":",2);if(!parts[1].startsWith(source+"/")||!parts[1].endsWith(".png"))throw new IllegalArgumentException("listing_role");String mapped=parts[0]+":"+prefix+parts[1].substring(source.length()+1,parts[1].length()-4);if(!RuntimeModelObservation.resourceId(mapped))throw new IllegalArgumentException("directory_output");if(mapped.equals(sprite))add(m,f,entry.getValue(),def,index,op,false);}}case "filter"->{JsonObject p=s.getAsJsonObject("pattern");String[] parts=sprite.split(":",2);boolean matches=(!p.has("namespace")||Pattern.compile(string(p.get("namespace"))).asPredicate().test(parts[0]))&&(!p.has("path")||Pattern.compile(string(p.get("path"))).asPredicate().test(parts[1]));if(matches&&!m.get("recipe_state").getAsString().equals("absent")){trace(m,def,index,op,"remove");m.addProperty("recipe_state","absent");for(String k:List.of("actual_candidate","external_source_candidate","winning_definition","winning_source_index"))nil(m,k);m.addProperty("status","missing_source");}}case "unstitch"->{String file=png(id(s.get("resource")));File base=effective(file);for(JsonElement region:s.getAsJsonArray("regions"))if(id(region.getAsJsonObject().get("sprite")).equals(sprite))add(m,file,base,def,index,op,true);}case "paletted_permutations"->{for(JsonElement texture:s.getAsJsonArray("textures")){String resource=id(texture),file=png(resource);File base=effective(file);for(String suffix:s.getAsJsonObject("permutations").keySet())if((resource+"_"+suffix).equals(sprite))add(m,file,base,def,index,op,true);}}default->throw new IllegalStateException();}
                    }
                }
            }
        }
        Captured run(){JsonObject atlas=obj();atlas.addProperty("atlas_id",BLOCKS);atlas.addProperty("info_id","minecraft:blocks");atlas.addProperty("status","complete");atlas.addProperty("excluded_recipe",false);atlas.add("definitions",new JsonArray());atlas.add("reason_codes",new JsonArray());boolean hasBlocks=false;Set<String> seen=new HashSet<>();for(JsonElement e:runtime.getAsJsonArray("sprites")){JsonObject sprite=e.getAsJsonObject(),m=mapping(sprite);mappings.add(m);String a=sprite.get("atlas_id").getAsString();if(a.equals(BLOCKS))hasBlocks=true;else{m.addProperty("status","unknown_atlas");if(seen.add(a)){JsonObject other=obj();other.addProperty("atlas_id",a);nil(other,"info_id");other.addProperty("status","unsupported");other.addProperty("excluded_recipe",false);other.add("definitions",new JsonArray());JsonArray r=new JsonArray();r.add("unknown_atlas");other.add("reason_codes",r);atlases.add(other);m.addProperty("status","unknown_atlas");}}}
            if(hasBlocks){atlases.add(atlas);try{List<File> definitions=stack(DEFINITION);if(definitions==null||definitions.isEmpty()||definitions.size()>limits.layers)throw new IllegalArgumentException("definition_layers");for(int i=0;i<definitions.size();i++){int asset=resource("definition",DEFINITION,definitions.get(i),i);JsonObject layer=obj();layer.addProperty("layer",i);layer.addProperty("asset_id",asset);atlas.getAsJsonArray("definitions").add(layer);if(excluded(definitions.get(i).provider()))atlas.addProperty("excluded_recipe",true);}for(JsonElement e:mappings){JsonObject m=e.getAsJsonObject();if(m.get("atlas_id").getAsString().equals(BLOCKS)){Object token=bundle.spriteTokens().get(m.get("sprite_handle").getAsInt());m.getAsJsonObject("sample").addProperty("identity_before",sampler.identity(BLOCKS,m.get("sprite_id").getAsString(),token));}}
                replay(atlas.getAsJsonArray("definitions"),atlas);
            }catch(Exception ex){reason(RuntimeModelObservation.safe(ex.getMessage()==null?"capture_error":ex.getMessage()));}
            if(incomplete){atlas.addProperty("status","incomplete");atlas.getAsJsonArray("reason_codes").add("recipe_incomplete");}
            for(JsonElement e:mappings){JsonObject m=e.getAsJsonObject();if(!m.get("atlas_id").getAsString().equals(BLOCKS))continue;if(incomplete){m.addProperty("status","incomplete");m.addProperty("recipe_state","unknown");m.getAsJsonArray("reason_codes").add("recipe_incomplete");continue;}JsonObject sample=m.getAsJsonObject("sample");Object token=bundle.spriteTokens().get(m.get("sprite_handle").getAsInt());try{if(sample.get("identity_before").isJsonNull()||!sample.get("identity_before").getAsBoolean()){m.addProperty("status","unknown_current_atlas");continue;}Boolean empty=sampler.metadataEmpty(token);RuntimeModelObservation.nullable(sample,"metadata_empty",empty);if(!Boolean.TRUE.equals(empty)){if(m.get("status").getAsString().equals("candidate"))m.addProperty("status","unsupported_static_metadata");continue;}if(!Set.of("candidate","unsupported_static_metadata").contains(m.get("status").getAsString())||!m.get("recipe_state").getAsString().equals("direct"))continue;Pixels pixels=sampler.pixels(token);long count=(long)pixels.width()*pixels.height();if(!pixels.rgba()||pixels.width()<=0||pixels.height()<=0||pixels.width()>2048||pixels.height()>2048||count>4194304||samplePixels+count>limits.pixels)throw new IllegalArgumentException("sample_budget");JsonObject observed=runtime.getAsJsonArray("sprites").get(m.get("sprite_handle").getAsInt()).getAsJsonObject();sample.addProperty("width",pixels.width());sample.addProperty("height",pixels.height());if(pixels.width()!=observed.get("width").getAsInt()||pixels.height()!=observed.get("height").getAsInt()){m.addProperty("status","unsupported_static_metadata");continue;}samplePixels+=count;sample.addProperty("pixel_sha256",pixelDigest(pixels));}catch(Exception ex){m.addProperty("status","incomplete");sample.getAsJsonArray("reason_codes").add("sample_failed");}}
            }
            for(JsonElement e:mappings){JsonObject m=e.getAsJsonObject();if(!m.get("atlas_id").getAsString().equals(BLOCKS))continue;try{boolean identity=sampler.identity(BLOCKS,m.get("sprite_id").getAsString(),bundle.spriteTokens().get(m.get("sprite_handle").getAsInt()));m.getAsJsonObject("sample").addProperty("identity_after",identity);if(!identity&&m.get("status").getAsString().equals("candidate"))m.addProperty("status","unknown_current_atlas");}catch(Exception ex){m.getAsJsonObject("sample").addProperty("identity_after",false);if(m.get("status").getAsString().equals("candidate"))m.addProperty("status","unknown_current_atlas");}}
            boolean safe=structure(root,limits.depth,limits.nodes);byte[] bytes=safe?RuntimeModelObservation.encode(root):new byte[0];if(!safe||bytes.length>8388608){root.add("resources",new JsonArray());assets.clear();for(JsonElement e:atlases){JsonObject a=e.getAsJsonObject();a.add("definitions",new JsonArray());a.addProperty("excluded_recipe",false);a.addProperty("status",a.get("info_id").isJsonNull()?"unsupported":"incomplete");}for(JsonElement e:mappings){JsonObject m=e.getAsJsonObject();m.add("trace",new JsonArray());for(String k:List.of("actual_candidate","external_source_candidate","winning_definition","winning_source_index"))nil(m,k);m.addProperty("recipe_state","unknown");m.addProperty("status",m.get("atlas_id").getAsString().equals(BLOCKS)?"incomplete":"unknown_atlas");}JsonArray fallbackOmissions=new JsonArray();JsonObject o=obj();o.addProperty("code","attribution_budget");o.addProperty("detail","small incomplete fallback");fallbackOmissions.add(o);root.add("omissions",fallbackOmissions);bytes=RuntimeModelObservation.encode(root);}return new Captured(bytes,assets);}
    }
    static Captured fixture(RuntimeModelObservation.Bundle bundle,Access access,Sampler sampler){JsonObject runtime=JsonParser.parseString(new String(bundle.bytes(),StandardCharsets.UTF_8)).getAsJsonObject();if(!runtime.get("origin").getAsString().equals("test_fixture"))throw new IllegalArgumentException("fixture origin required");return new Evaluation(bundle,access,sampler).run();}
    static Access access(ResourceManager manager){return new Access(){final IdentityHashMap<Resource,File> wrapped=new IdentityHashMap<>();File wrap(Resource r){return wrapped.computeIfAbsent(r,AtlasSourceAttribution::resourceFile);}public List<File> stack(String id){var values=manager.getResourceStack(ResourceLocation.parse(id));if(values.size()>64)throw new IllegalArgumentException("stack bound");return values.stream().map(this::wrap).toList();}public File effective(String id){return manager.getResource(ResourceLocation.parse(id)).map(this::wrap).orElse(null);}public Map<String,File> list(String prefix){Map<String,File> out=new TreeMap<>();var values=manager.listResources(prefix,id->id.getPath().endsWith(".png"));if(values.size()>4096)throw new IllegalArgumentException("listing_budget");values.forEach((k,v)->out.put(k.toString(),wrap(v)));return out;}};}
    static Captured capture(Minecraft mc,RuntimeModelObservation.Bundle bundle){if(!mc.isSameThread())throw new IllegalStateException("client thread required");Access access=access(mc.getResourceManager());
        Sampler sampler=new Sampler(){public boolean identity(String atlas,String sprite,Object token){return token instanceof TextureAtlasSprite observed&&mc.getModelManager().getAtlas(ResourceLocation.parse(atlas)).getSprite(ResourceLocation.parse(sprite))==observed&&observed.contents().name().toString().equals(sprite);}public Boolean metadataEmpty(Object token){return ((TextureAtlasSprite)token).contents().metadata()==ResourceMetadata.EMPTY;}public Pixels pixels(Object token){NativeImage image=((TextureAtlasSprite)token).contents().getOriginalImage();return new Pixels(){public int width(){return image.getWidth();}public int height(){return image.getHeight();}public boolean rgba(){return image.format()==NativeImage.Format.RGBA;}public int abgr(int x,int y){return image.getPixelRGBA(x,y);}};}};return new Evaluation(bundle,access,sampler).run();}
}
