package dev.integratepbr.model.discovery;
import com.google.gson.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.*;

/** Synthetic callbacks use the production capture and attachment path; never a client claim. */
public final class RuntimeModelObservationRegression {
    static void check(boolean value,String reason){if(!value)throw new AssertionError(reason);}
    static JsonObject parsed(byte[] bytes){return JsonParser.parseString(new String(bytes,StandardCharsets.UTF_8)).getAsJsonObject();}
    static final class Fixture implements RuntimeModelObservation.Query {
        final boolean item;final JsonObject owner,context,arm;final Object base=new Object(),resolved=new Object(),transformed=new Object(),type=new Object();
        final List<String> calls=new ArrayList<>();int passCount=1,typeCount=2,quadCount=1,tintIndex=2;boolean custom,unsupported,throwQuery,nullQuads,missing,throwTransform,nullType,throwTint,badSibling,nullPackedSibling;int[] packed=new int[32];
        RuntimeModelObservation.Sprite sprite=new RuntimeModelObservation.Sprite(new Object(),"fixture:unmatched_sprite","minecraft:textures/atlas/blocks.png",11,5,.125,.375,.25,.75);
        Fixture(JsonObject owner){this.owner=owner.deepCopy();item=owner.get("kind").getAsString().equals("item");context=RuntimeModelObservation.context(item,"fixture:dimension",123);arm=new JsonObject();
            if(item){arm.addProperty("stack_count",3);JsonObject encoding=new JsonObject();encoding.addProperty("id",owner.get("id").getAsString());encoding.addProperty("count",3);encoding.addProperty("fraction",1.0e-4);encoding.addProperty("unicode","\u96ea\n\u03b1");RuntimeModelObservation.encoding(arm,encoding);arm.addProperty("entity_id",7);arm.addProperty("display_context","FIRST_PERSON_RIGHT_HAND");arm.addProperty("left_hand",false);arm.addProperty("model_seed",11);arm.addProperty("quad_seed",42);arm.addProperty("pose_scope","camera_transform_then_item_center");arm.add("pose_matrix",RuntimeModelObservation.array(1,0,0,0,0,1,0,0,0,0,1,0,-.5,-.5,-.5,1));for(String k:List.of("base_model_handle","resolved_model_handle","transformed_model_handle"))arm.add(k,JsonNull.INSTANCE);}
            else{JsonArray pos=new JsonArray();pos.add(2);pos.add(-3);pos.add(4);arm.add("position",pos);JsonObject properties=new JsonObject();properties.addProperty("facing","north");arm.add("state_properties",properties);arm.addProperty("render_shape","MODEL");arm.addProperty("state_seed",987654321L);arm.add("model_handle",JsonNull.INSTANCE);arm.addProperty("model_data_origin","client_level_model_data_manager");arm.addProperty("input_model_data_empty",false);arm.addProperty("derived_model_data_empty",false);arm.addProperty("chunk_mesh_reproduction",false);arm.addProperty("block_entity_renderer_included",false);}
            context.add(item?"item":"block",arm);
            float[][] uv={{.35f,.3f},{.15f,.7f},{.15f,.3f},{.35f,.7f}};
            for(int v=0;v<4;v++){int i=v*8;packed[i]=Float.floatToRawIntBits(v+.25f);packed[i+1]=Float.floatToRawIntBits(-v-.5f);packed[i+2]=Float.floatToRawIntBits(.125f);packed[i+3]=0x10203040;packed[i+4]=Float.floatToRawIntBits(uv[v][0]);packed[i+5]=Float.floatToRawIntBits(uv[v][1]);}
        }
        public JsonObject owner(){return owner;}public JsonObject context(){return context;}public boolean item(){return item;}
        public Object base(){calls.add("base");return item?base:null;}public Object resolved(){calls.add("resolved");return missing?null:resolved;}public Object transformed(Object m){check(m==resolved,"resolved token forwarded");calls.add("transform");if(throwTransform)throw new IllegalStateException("fixture transform error");return transformed;}
        public boolean custom(Object m){return custom;}public boolean dispatchUnsupported(){return unsupported;}
        public List<?> passes(Object m){check(m==transformed,"transformed token forwarded");calls.add("passes");return Collections.nCopies(passCount,transformed);}
        public List<?> types(Object m){check(m==transformed,"pass token forwarded");calls.add("types");return Collections.nCopies(typeCount,nullType?null:type);}
        public List<RuntimeModelObservation.Quad> quads(Object m,Object t,String bucket,long seed){check(m==transformed&&t==type,"model/type forwarded");check(seed==(item?42:987654321L),"seed reset");calls.add((item?"item3:":"block5:")+bucket);if(throwQuery)throw new IllegalStateException("fixture query error");if(nullQuads)return null;if(nullPackedSibling)return Arrays.asList(new RuntimeModelObservation.Quad(packed,sprite,"north",true,false,tintIndex),new RuntimeModelObservation.Quad(null,sprite,"north",true,false,tintIndex),new RuntimeModelObservation.Quad(packed,sprite,"north",true,false,tintIndex));if(badSibling)return Arrays.asList(new RuntimeModelObservation.Quad(packed,sprite,"north",true,false,tintIndex),null,new RuntimeModelObservation.Quad(packed,sprite,"north",true,false,tintIndex));return Collections.nCopies(quadCount,new RuntimeModelObservation.Quad(packed,sprite,"north",true,false,tintIndex));}
        public int tint(int index){check(index==tintIndex,"tint index");if(throwTint)throw new IllegalStateException("fixture tint error");return 0x55667788;}
    }
    static JsonObject owner(String kind,String id){JsonObject o=new JsonObject();o.addProperty("kind",kind);o.addProperty("id",id);return o;}
    public static void run(ResourceSnapshot.Captured itemSource,ResourceSnapshot.Captured blockSource,Path output) throws Exception {
        var property=new net.minecraft.world.level.block.state.properties.Property<Integer>("named",Integer.class){public Collection<Integer> getPossibleValues(){return List.of(7);}public String getName(Integer value){return "named_"+value;}public Optional<Integer> getValue(String value){return Optional.of(7);}};
        Map<net.minecraft.world.level.block.state.properties.Property<?>,Comparable<?>> values=new HashMap<>();values.put(property,7);List<String> propertyErrors=new ArrayList<>();check(RuntimeModelObservation.stateProperties(values,propertyErrors).get("named").getAsString().equals("named_7"),"Property.getName differs from toString");
        var emptyProperty=new net.minecraft.world.level.block.state.properties.Property<Integer>("empty",Integer.class){public Collection<Integer> getPossibleValues(){return List.of(7);}public String getName(Integer value){return "";}public Optional<Integer> getValue(String value){return Optional.of(7);}};values.put(emptyProperty,7);check(!RuntimeModelObservation.stateProperties(values,propertyErrors).has("empty")&&propertyErrors.contains("state_property_limit"),"actual empty property omitted");
        Fixture item=new Fixture(itemSource.manifest().getAsJsonObject("selected_owner"));byte[] itemBytes=RuntimeModelObservation.fixture(item);JsonObject observation=parsed(itemBytes);
        check(observation.get("origin").getAsString().equals("test_fixture"),"fixture origin");check(observation.get("status").getAsString().equals("complete"),"item complete");check(observation.getAsJsonArray("models").size()==3,"replacement handles");check(observation.getAsJsonArray("queries").size()==14&&observation.getAsJsonArray("quads").size()==14,"duplicate type occurrences seven buckets");
        JsonObject q=observation.getAsJsonArray("quads").get(0).getAsJsonObject();check(q.getAsJsonObject("tint").get("raw_color").getAsInt()==0x55667788,"tint separate");check(q.getAsJsonArray("decoded_vertices").get(0).getAsJsonObject().get("vertex_color").getAsInt()==0x10203040,"packed color retained");
        item.packed[0]=0;check(parsed(itemBytes).getAsJsonArray("quads").get(0).getAsJsonObject().getAsJsonArray("packed_vertices").get(0).getAsInt()!=0,"detached data");
        Fixture block=new Fixture(blockSource.manifest().getAsJsonObject("selected_owner"));byte[] blockBytes=RuntimeModelObservation.fixture(block);check(parsed(blockBytes).get("status").getAsString().equals("complete"),"block complete");check(block.calls.contains("block5:null"),"block distinct query callback");
        for(String mode:List.of("missing","custom","unsupported","throw","null","oversized","layout","nan","sprite")){Fixture f=new Fixture(itemSource.manifest().getAsJsonObject("selected_owner"));switch(mode){case "missing"->f.missing=true;case "custom"->f.custom=true;case "unsupported"->f.unsupported=true;case "throw"->f.throwQuery=true;case "null"->f.nullQuads=true;case "oversized"->{f.passCount=9;f.typeCount=17;f.quadCount=129;}case "layout"->f.packed=new int[65];case "nan"->f.packed[0]=0x7fc00000;case "sprite"->f.sprite=null;}
            JsonObject result=parsed(RuntimeModelObservation.fixture(f));check(!result.get("status").getAsString().equals("complete"),"failure status "+mode);check(result.getAsJsonArray("queries").size()<=896&&result.getAsJsonArray("quads").size()<=2048,"budgets "+mode);}
        Fixture zero=new Fixture(itemSource.manifest().getAsJsonObject("selected_owner"));zero.quadCount=0;check(parsed(RuntimeModelObservation.fixture(zero)).get("status").getAsString().equals("complete"),"successful empty queries");
        Fixture nonModel=new Fixture(blockSource.manifest().getAsJsonObject("selected_owner"));nonModel.unsupported=true;nonModel.missing=true;nonModel.arm.addProperty("render_shape","INVISIBLE");check(parsed(RuntimeModelObservation.fixture(nonModel)).get("status").getAsString().equals("unsupported"),"non MODEL unsupported");check(!nonModel.calls.contains("passes"),"no renderer call unsupported");
        List<Map.Entry<String,byte[]>> partials=new ArrayList<>();
        for(String mode:List.of("oversized_packed","bad_sibling","negative_tint","untinted","tint_error","null_type","transform_error","unsafe_encoding","deep_encoding","node_limit","byte_limit","property_limit","null_packed_sibling","empty_property")){
            Fixture f=new Fixture(itemSource.manifest().getAsJsonObject("selected_owner"));
            switch(mode){case "oversized_packed"->{f.packed=new int[1000000];var detached=new RuntimeModelObservation.Quad(f.packed,f.sprite,"north",true,false,2);check(detached.vertices()==null&&detached.packedCount()==1000000,"oversized not retained");}case "bad_sibling"->f.badSibling=true;case "negative_tint"->f.tintIndex=-2;case "untinted"->f.tintIndex=-1;case "tint_error"->f.throwTint=true;case "null_type"->f.nullType=true;case "transform_error"->f.throwTransform=true;case "unsafe_encoding"->{JsonObject unsafe=new JsonObject();unsafe.addProperty("invalid",Double.NaN);check(!RuntimeModelObservation.encoding(f.arm,unsafe),"unsafe encoding rejected");}case "deep_encoding"->{JsonObject deep=new JsonObject(),cur=deep;for(int i=0;i<40;i++){JsonObject child=new JsonObject();cur.add("x",child);cur=child;}check(!RuntimeModelObservation.encoding(f.arm,deep),"deep encoding rejected");}case "node_limit"->{f.passCount=8;f.typeCount=16;f.quadCount=128;}case "byte_limit"->{JsonObject big=new JsonObject();big.addProperty("large","x".repeat(65537));check(!RuntimeModelObservation.encoding(f.arm,big),"large encoding rejected");}case "null_packed_sibling"->f.nullPackedSibling=true;case "empty_property"->{f=new Fixture(blockSource.manifest().getAsJsonObject("selected_owner"));JsonObject props=new JsonObject();props.addProperty("valid","named");props.addProperty("","bad");props.addProperty("empty_value","");f.arm.add("state_properties",props);}case "property_limit"->{f=new Fixture(blockSource.manifest().getAsJsonObject("selected_owner"));JsonObject props=new JsonObject();for(int i=0;i<65;i++)props.addProperty("p"+i,"v");f.arm.add("state_properties",props);}}
            byte[] data=RuntimeModelObservation.fixture(f);JsonObject r=parsed(data);check(RuntimeModelObservation.safeTree(r,32,100000)&&data.length<=4194304,"safe final "+mode);
            if(mode.equals("negative_tint")||mode.equals("untinted"))check(r.get("status").getAsString().equals("complete"),"tint successful "+mode);else check(r.get("status").getAsString().equals("incomplete"),"partial status "+mode);
            if(mode.equals("transform_error")){JsonObject a=r.getAsJsonObject("context").getAsJsonObject("item");check(!a.get("base_model_handle").isJsonNull()&&!a.get("resolved_model_handle").isJsonNull(),"prior stage preserved");}
            if(mode.equals("bad_sibling")||mode.equals("null_packed_sibling"))check(r.getAsJsonArray("quads").size()==28,"valid siblings retained");
            partials.add(Map.entry(mode,data));
        }
        if(output!=null){for(var entry:partials){JsonObject o=parsed(entry.getValue()).getAsJsonObject("selected_owner");ResourceSnapshot.Captured source=o.get("kind").getAsString().equals("block")?blockSource:itemSource;ResourceSnapshot.export(ResourceSnapshot.withRuntimeObservation(source,entry.getValue()),output.resolve(entry.getKey()));}ResourceSnapshot.export(ResourceSnapshot.withRuntimeObservation(itemSource,itemBytes),output.resolve("item"));ResourceSnapshot.export(ResourceSnapshot.withRuntimeObservation(blockSource,blockBytes),output.resolve("block"));var emptyOwner=ResourceSnapshotRegression.owner("fixture:no_source",ResourceSnapshot.Kind.ITEM);var empty=ResourceSnapshot.capture(emptyOwner,List.of(emptyOwner),key->List.of(),ResourceSnapshot.Limits.defaults());Fixture unmatched=new Fixture(empty.manifest().getAsJsonObject("selected_owner"));ResourceSnapshot.export(ResourceSnapshot.withRuntimeObservation(empty,RuntimeModelObservation.fixture(unmatched)),output.resolve("empty"));}
    }
}
